name: Hello CI
on:
  push:
  pull_request:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Say hello (will fail)
        run: exit 1

      - name: Show runner info
        run: |
          echo "Runner OS: $RUNNER_OS"
          uname -a
